name: Rust

on:
  push:
    branches: ["main", "test"]
  pull_request:
    branches: ["main", "test"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2

      - name: Update system and development tools
        run: |
          sudo apt install -y libasound2-dev pkg-config libudev-dev;
          rustup update
          cargo update

      - name: Rust Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
